Use movies

Select NAME, BIRTHDATE 
From MOVIESTAR m  
	JOIN STARSIN s On m.NAME = s.STARNAME 
	JOIN MOVIE m2 On m2.TITLE = s.MOVIETITLE 
Where NAME NOT LIKE '%Jr.%' and m2.INCOLOR  = 'Y'
Group By NAME, BIRTHDATE 
HAVING COUNT(m2.INCOLOR) >= 1
Order By BIRTHDATE DESC, NAME ASC

